In [1]:
# Import necessary libraries
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import random

# Load diabetes dataset
diabetes = datasets.load_diabetes()
X = diabetes.data
y = diabetes.target

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

# Standardize features by removing the mean and scaling to unit variance
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

# Define the objective function for PSO
def objective_function(feature_weights):
    selected_features = np.where(feature_weights > 0.5, 1, 0)
    X_train_selected = X_train_std[:, selected_features == 1]
    X_test_selected = X_test_std[:, selected_features == 1]
    
    if X_train_selected.shape[1] == 0:
        return 1
    
    svm_model = svm.SVR()
    svm_model.fit(X_train_selected, y_train)
    y_pred = svm_model.predict(X_test_selected)
    mse = np.mean((y_pred - y_test) ** 2)
    return mse

# Define the PSO parameters
n_particles = 50
n_iterations = 100
n_features = X.shape[1]
feature_weights = np.random.rand(n_particles, n_features)

# Initialize the velocity and best position for each particle
velocity = np.zeros((n_particles, n_features))
best_position = feature_weights.copy()
best_fitness = np.zeros(n_particles)

# Run the PSO algorithm
for i in range(n_iterations):
    for j in range(n_particles):
        fitness = objective_function(feature_weights[j])
        if fitness < best_fitness[j]:
            best_fitness[j] = fitness
            best_position[j] = feature_weights[j]
        
        # Update the velocity and position of each particle
        velocity[j] = 0.5 * velocity[j] + 1.5 * np.random.rand(n_features) * (best_position[j] - feature_weights[j]) + 1.5 * np.random.rand(n_features) * (np.mean(best_position, axis=0) - feature_weights[j])
        feature_weights[j] = feature_weights[j] + velocity[j]
        
        # Ensure the feature weights are within the range [0, 1]
        feature_weights[j] = np.clip(feature_weights[j], 0, 1)
    
    # Print the MSE in every iteration
    best_particle_index = np.argmin(best_fitness)
    best_features = np.where(best_position[best_particle_index] > 0.5, 1, 0)
    X_train_selected = X_train_std[:, best_features == 1]
    X_test_selected = X_test_std[:, best_features == 1]
    svm_model = svm.SVR()
    svm_model.fit(X_train_selected, y_train)
    y_pred = svm_model.predict(X_test_selected)
    mse = np.mean((y_pred - y_test) ** 2)
    print("Iteration:", i+1, "MSE:", mse)

# Select the features with the highest weights
best_particle_index = np.argmin(best_fitness)
best_features = np.where(best_position[best_particle_index] > 0.5, 1, 0)

# Print the best features
print("Best Features:")
for i in range(len(best_features)):
    if best_features[i] == 1:
        print(diabetes.feature_names[i])

# Train an SVM model with the selected features
X_train_selected = X_train_std[:, best_features == 1]
X_test_selected = X_test_std[:, best_features == 1]
svm_model = svm.SVR()
svm_model.fit(X_train_selected, y_train)
y_pred = svm_model.predict(X_test_selected)

# Evaluate the model
mse = np.mean((y_pred - y_test) ** 2)
print("Final MSE:", mse)


Iteration: 1 MSE: 4142.384909298182
Iteration: 2 MSE: 4142.384909298182
Iteration: 3 MSE: 4142.384909298182
Iteration: 4 MSE: 4142.384909298182
Iteration: 5 MSE: 4142.384909298182
Iteration: 6 MSE: 4142.384909298182
Iteration: 7 MSE: 4142.384909298182
Iteration: 8 MSE: 4142.384909298182
Iteration: 9 MSE: 4142.384909298182
Iteration: 10 MSE: 4142.384909298182
Iteration: 11 MSE: 4142.384909298182
Iteration: 12 MSE: 4142.384909298182
Iteration: 13 MSE: 4142.384909298182
Iteration: 14 MSE: 4142.384909298182
Iteration: 15 MSE: 4142.384909298182
Iteration: 16 MSE: 4142.384909298182
Iteration: 17 MSE: 4142.384909298182
Iteration: 18 MSE: 4142.384909298182
Iteration: 19 MSE: 4142.384909298182
Iteration: 20 MSE: 4142.384909298182
Iteration: 21 MSE: 4142.384909298182
Iteration: 22 MSE: 4142.384909298182
Iteration: 23 MSE: 4142.384909298182
Iteration: 24 MSE: 4142.384909298182
Iteration: 25 MSE: 4142.384909298182
Iteration: 26 MSE: 4142.384909298182
Iteration: 27 MSE: 4142.384909298182
Iteration:

In [10]:
y_pred

array([130.94328906, 133.90754734, 140.13646762, 123.59473301,
       154.9573742 , 159.05145937, 155.98501378, 150.50994367,
       153.00073826, 145.58697085, 143.40710233, 150.17578529,
       141.08317007, 123.93260987, 155.33562306, 151.26750459,
       151.74785476, 128.33107881, 144.18060175, 140.74543613,
       160.35721649, 127.34517125, 134.07327244, 130.90853661,
       126.84395258, 142.18287228, 125.28376813, 136.62608521,
       148.42032491, 156.26664709, 140.34308076, 138.02525239,
       137.07730095, 129.44171336, 142.33956385, 154.07758931,
       134.77249215, 153.18472049, 141.99633581, 151.87895615,
       134.86836036, 142.18242069, 141.42461374, 139.5838023 ,
       134.02933822, 155.52870973, 130.14099534, 139.24667416,
       143.68481047, 156.57838477, 121.47225546, 144.33058402,
       142.21658846, 133.05897868, 156.3305055 , 141.68144318,
       141.36825981, 145.98071809, 125.6391798 , 123.21762253,
       129.84092189, 142.14324161, 153.42839163, 124.90

In [5]:
best_features = np.where(best_position[best_particle_index] > 0.5, 1, 0)

In [6]:
best_features

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [8]:
feature_weights

array([[0.70156636, 0.77629109, 0.33040586, 0.69675652, 0.47170618,
        0.63360587, 0.65927927, 0.43680006, 0.        , 0.18876185],
       [0.12958658, 0.72185431, 0.31201072, 0.47912478, 0.69453659,
        0.80067516, 0.3635948 , 0.4947596 , 0.48464731, 0.5656721 ],
       [0.56149461, 0.67999595, 0.28459568, 0.59260651, 0.38097127,
        0.57682002, 0.70335035, 0.01583314, 0.57215028, 0.33900607],
       [0.52591554, 0.45289118, 0.49470125, 0.        , 0.52808399,
        0.48770717, 0.45646771, 0.83724422, 0.49445284, 0.52318663],
       [0.50415814, 0.50896722, 0.8425117 , 0.52431638, 0.18184963,
        0.3120512 , 0.44646005, 1.        , 0.50895349, 0.37023035],
       [0.57418294, 0.43995817, 0.        , 0.55702595, 0.53280179,
        0.44417018, 0.46069484, 0.06155667, 0.51864615, 0.32207991],
       [0.59058829, 0.46225198, 0.22693103, 0.57077575, 0.38427296,
        0.68391935, 0.41095265, 0.46201197, 0.43956459, 0.58161176],
       [0.28314229, 0.08244229, 0.4343165

In [9]:
best_position

array([[0.88986097, 0.71632205, 0.31299585, 0.83332024, 0.44349886,
        0.60315643, 0.72168017, 0.40168689, 0.00502976, 0.02894373],
       [0.15626862, 0.87773262, 0.25643536, 0.47983627, 0.8754173 ,
        0.83605334, 0.29935628, 0.95304466, 0.42965008, 0.86250094],
       [0.97885076, 0.9405289 , 0.20228002, 0.96114211, 0.42832054,
        0.55018186, 0.75931245, 0.03495906, 0.61889945, 0.00625341],
       [0.51258676, 0.45889584, 0.09434196, 0.04178515, 0.4288107 ,
        0.47728392, 0.12217391, 0.8818225 , 0.50894082, 0.67676039],
       [0.51458593, 0.59580461, 0.95520027, 0.47061926, 0.10962499,
        0.30261052, 0.05098682, 0.87650788, 0.40623699, 0.27336503],
       [0.95070275, 0.43856743, 0.01164178, 0.5406283 , 0.53616007,
        0.3715047 , 0.4147581 , 0.13154436, 0.53232251, 0.94303646],
       [0.98981079, 0.43626455, 0.18122352, 0.63348306, 0.34302912,
        0.82688202, 0.32541875, 0.5600287 , 0.81419496, 0.70823565],
       [0.30470873, 0.08620023, 0.4323438

In [11]:
best_position

array([[0.88986097, 0.71632205, 0.31299585, 0.83332024, 0.44349886,
        0.60315643, 0.72168017, 0.40168689, 0.00502976, 0.02894373],
       [0.15626862, 0.87773262, 0.25643536, 0.47983627, 0.8754173 ,
        0.83605334, 0.29935628, 0.95304466, 0.42965008, 0.86250094],
       [0.97885076, 0.9405289 , 0.20228002, 0.96114211, 0.42832054,
        0.55018186, 0.75931245, 0.03495906, 0.61889945, 0.00625341],
       [0.51258676, 0.45889584, 0.09434196, 0.04178515, 0.4288107 ,
        0.47728392, 0.12217391, 0.8818225 , 0.50894082, 0.67676039],
       [0.51458593, 0.59580461, 0.95520027, 0.47061926, 0.10962499,
        0.30261052, 0.05098682, 0.87650788, 0.40623699, 0.27336503],
       [0.95070275, 0.43856743, 0.01164178, 0.5406283 , 0.53616007,
        0.3715047 , 0.4147581 , 0.13154436, 0.53232251, 0.94303646],
       [0.98981079, 0.43626455, 0.18122352, 0.63348306, 0.34302912,
        0.82688202, 0.32541875, 0.5600287 , 0.81419496, 0.70823565],
       [0.30470873, 0.08620023, 0.4323438